// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game.data;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Properties;
import java.util.stream.Collectors;

/**
 * Loads {@code /config.properties} from the classpath on construction and exposes helpers to read
 * properties and arbitrary UTF-8 text resources (e.g. CSV paths configured in properties).
 */
public class DataLoader {

    private static Properties properties = new Properties();

    /**
     * Loads global properties from {@code /config.properties}.
     *
     * @throws IllegalStateException if the resource is missing or cannot be read
     */
    public DataLoader() {
        try (InputStream input = getClass().getResourceAsStream("/config.properties")) {
            if (input == null) {
                throw new IllegalStateException("Missing classpath resource /config.properties");
            }
            properties.load(input);
        } catch (IOException ex) {
            throw new IllegalStateException("Could not load /config.properties", ex);
        }
    }

    /**
     * @param key property key from {@code config.properties}
     * @return value or {@code null} if unset
     */
    public String getProperty(String key) {
        return properties.getProperty(key, null);
    }

    /**
     * Reads an entire classpath resource as UTF-8 text, with lines rejoined using the platform line separator.
     *
     * @param fileName path as used with {@link Class#getResourceAsStream(String)} (e.g. {@code "/cards.csv"})
     * @return full file contents
     * @throws IllegalArgumentException if the resource does not exist
     * @throws RuntimeException         if reading fails
     */
    public String readResourceFile(String fileName) {
        InputStream inputStream = getClass().getResourceAsStream(fileName);
        if (inputStream == null) {
            throw new IllegalArgumentException("Resource not found: " + fileName);
        }

        try (BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8))) {
            return reader.lines().collect(Collectors.joining(System.lineSeparator()));
        } catch (Exception e) {
            throw new RuntimeException("Error reading resource file " + fileName, e);
        }
    }
}
