// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game;

import com.splendor.web.game.model.Card;

import java.util.ArrayList;
import java.util.Random;

/**
 * Utility for drawing random cards from closed decks into face-up display rows (up to four per level).
 * Used during initial {@link WebGameSetupService setup} and when {@link WebCardRulesService} refills after a purchase.
 */
final class CardSupply {

    private static final Random RAND = new Random();

    /** Not instantiable. */
    private CardSupply() {}

    /**
     * Repeatedly removes a random card from {@code closed} and appends to {@code open} until the row has four cards
     * or the deck is empty.
     *
     * @param closed deck to draw from (mutated)
     * @param open   face-up row to fill (mutated)
     */
    static void transferRandomFaceUp(ArrayList<Card> closed, ArrayList<Card> open) {
        while (open.size() < 4 && !closed.isEmpty()) {
            Card c = closed.remove(RAND.nextInt(closed.size()));
            open.add(c);
        }
    }
}
