// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game;

import org.springframework.stereotype.Service;
import com.splendor.web.game.model.Noble;

import java.util.List;

/**
 * Web game façade: delegates to setup, token rules, card rules, turn flow, CPU, and outcome services
 * so controllers depend on one bean while logic stays split by responsibility.
 */
@Service
public class GameService {

    private final WebGameSetupService setup;
    private final WebTokenRulesService tokenRules;
    private final WebCardRulesService cardRules;
    private final TurnPhaseService turnPhase;
    private final CpuTurnService cpuTurn;
    private final GameOutcomeService outcomes;

    /**
     * Wires the façade to all specialized game services.
     *
     * @param setup      new-game construction
     * @param tokenRules take/return gem rules
     * @param cardRules  reserve and purchase rules
     * @param turnPhase  end-of-turn nobles and game-end checks
     * @param cpuTurn    CPU play-by-play execution
     * @param outcomes   winner calculation
     */
    public GameService(WebGameSetupService setup,
                       WebTokenRulesService tokenRules,
                       WebCardRulesService cardRules,
                       TurnPhaseService turnPhase,
                       CpuTurnService cpuTurn,
                       GameOutcomeService outcomes) {
        this.setup = setup;
        this.tokenRules = tokenRules;
        this.cardRules = cardRules;
        this.turnPhase = turnPhase;
        this.cpuTurn = cpuTurn;
        this.outcomes = outcomes;
    }

    /**
     * @param playersInTurnOrder seats in turn order (youngest first)
     * @return new session with board initialized
     */
    public GameSession newGame(List<PlayerSetup> playersInTurnOrder) {
        return setup.newGame(playersInTurnOrder);
    }

    /**
     * @param session current game
     * @param colors  three distinct valid gem colours with bank availability
     * @return {@code true} if the take was applied
     */
    public boolean take3Tokens(GameSession session, List<String> colors) {
        return tokenRules.take3Tokens(session, colors);
    }

    /**
     * @param session current game
     * @param color   gem colour with at least four tokens in the bank
     * @return {@code true} if two tokens were taken
     */
    public boolean take2Tokens(GameSession session, String color) {
        return tokenRules.take2Tokens(session, color);
    }

    /**
     * @param session current game
     * @param level   card level (1–3)
     * @param index   index in the open row
     * @return {@code true} if reserved (and gold given if available)
     */
    public boolean reserveCardFromTable(GameSession session, int level, int index) {
        return cardRules.reserveCardFromTable(session, level, index);
    }

    /**
     * @param session current game
     * @param level   deck level (1–3)
     * @return {@code true} if a card was drawn from the top of the closed deck into reserves
     */
    public boolean reserveCardFromDeck(GameSession session, int level) {
        return cardRules.reserveCardFromDeck(session, level);
    }

    /**
     * @param session current game
     * @param level   card level
     * @param index   index in the open row
     * @return {@code true} if the purchase succeeded
     */
    public boolean buyCardFromTable(GameSession session, int level, int index) {
        return cardRules.buyCardFromTable(session, level, index);
    }

    /**
     * @param session       current game
     * @param reservedIndex index in the current player's reserved list
     * @return {@code true} if the purchase succeeded
     */
    public boolean buyReservedCard(GameSession session, int reservedIndex) {
        return cardRules.buyReservedCard(session, reservedIndex);
    }

    /**
     * @param session        current game
     * @param tokensToReturn gem colours to return from the current player to the bank
     */
    public void executeReturnTokens(GameSession session, List<String> tokensToReturn) {
        tokenRules.executeReturnTokens(session, tokensToReturn);
    }

    /**
     * @param session current game
     * @return noble acquired this turn, if any
     */
    public Noble finishTurn(GameSession session) {
        return turnPhase.finishTurn(session);
    }

    /**
     * @param gs finished game state
     * @return winning player id(s) after tie-break
     */
    public List<Integer> computeWinnerPlayerIds(GameSession gs) {
        return outcomes.computeWinnerPlayerIds(gs);
    }

    /**
     * Runs exactly one CPU turn (mutates {@code gs}) and returns log lines for the UI.
     *
     * @param gs current game; current player must be CPU
     * @return human-readable steps for {@code cpu-turn} view
     */
    public List<String> executeOneCPUTurn(GameSession gs) {
        return cpuTurn.executeOneCPUTurn(gs);
    }
}
