// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game;

import org.springframework.stereotype.Service;
import com.splendor.web.game.model.Player;

import java.util.List;

/**
 * Computes winner identity after a game ends, including Splendor tie-breaking rules.
 */
@Service
public class GameOutcomeService {

    /**
     * Finds all player IDs tied for the win: highest prestige, then fewest bought cards among those tied on points.
     *
     * @param gs finished or ending game state
     * @return IDs of {@link com.splendor.web.game.model.Player}s sharing the win (tie-break applied)
     */
    public List<Integer> computeWinnerPlayerIds(GameSession gs) {
        int maxPts = gs.getPlayers().stream().mapToInt(Player::getPrestigePoints).max().orElse(0);
        var tied = gs.getPlayers().stream().filter(p -> p.getPrestigePoints() == maxPts).toList();
        int minCards = tied.stream().mapToInt(p -> p.getBoughtCards().size()).min().orElse(0);
        return tied.stream().filter(p -> p.getBoughtCards().size() == minCards).map(Player::getPlayerID).toList();
    }
}
