// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game;

import com.splendor.web.game.model.Card;
import com.splendor.web.game.model.Noble;
import com.splendor.web.game.model.Player;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Serializable aggregate of everything needed for one Splendor game in an HTTP session:
 * gem bank counts, closed and open development cards by level, available nobles, players,
 * current turn index, and end-game flags. Stored under {@code "gameSession"} for the web app.
 * <p>
 * Player list order is turn order: index {@code 0} goes first (youngest), the last player is oldest.
 */
public class GameSession implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Map<String, Integer> tokenCounts = new HashMap<>();
    private final ArrayList<Card> closedLevel1 = new ArrayList<>();
    private final ArrayList<Card> closedLevel2 = new ArrayList<>();
    private final ArrayList<Card> closedLevel3 = new ArrayList<>();
    private final ArrayList<Card> openLevel1 = new ArrayList<>();
    private final ArrayList<Card> openLevel2 = new ArrayList<>();
    private final ArrayList<Card> openLevel3 = new ArrayList<>();
    private final ArrayList<Noble> availNobles = new ArrayList<>();

    private final ArrayList<Player> players = new ArrayList<>();
    private int currentPlayerIndex = 0;
    private boolean gameOver = false;
    private boolean finalRound = false;
    private final int pointsToWin;
    private final int maxTokensPerPlayer;

    /**
     * Initializes bank token counts and creates {@link Player} instances from setup; card and noble lists start empty
     * until {@link WebGameSetupService} loads them.
     *
     * @param playersInTurnOrder first = youngest (starts), last = oldest
     * @param pointsToWin        prestige required to trigger the final round
     * @param maxTokensPerPlayer maximum gems (including gold) a player may hold before returning excess
     * @param tokenPerGem        initial count per non-gold colour in the bank
     * @param goldCount          initial gold tokens in the bank
     */
    public GameSession(List<PlayerSetup> playersInTurnOrder, int pointsToWin, int maxTokensPerPlayer,
                       int tokenPerGem, int goldCount) {
        this.pointsToWin = pointsToWin;
        this.maxTokensPerPlayer = maxTokensPerPlayer;

        for (String color : new String[]{"black", "blue", "green", "red", "white"}) {
            tokenCounts.put(color, tokenPerGem);
        }
        tokenCounts.put("gold", goldCount);

        int id = 1;
        for (PlayerSetup setup : playersInTurnOrder) {
            players.add(new Player(id++, setup.human(), setup.name()));
        }
    }

    /**
     * @param gemType gem colour or {@code "gold"} (case-insensitive)
     * @return number of tokens of that type currently in the bank
     */
    public int getTokenCount(String gemType) {
        return tokenCounts.getOrDefault(gemType.toLowerCase(), 0);
    }

    /**
     * Removes tokens from the bank (e.g. when a player takes gems).
     *
     * @param gemType gem colour or gold
     * @param amount  positive count to subtract
     */
    public void removeTokens(String gemType, int amount) {
        tokenCounts.merge(gemType.toLowerCase(), amount, (a, b) -> a - b);
    }

    /**
     * Returns tokens to the bank (e.g. when a player pays for a card or returns excess).
     *
     * @param gemType gem colour or gold
     * @param amount  count to add
     */
    public void addTokens(String gemType, int amount) {
        tokenCounts.merge(gemType.toLowerCase(), amount, Integer::sum);
    }

    /** @return mutable face-up level-1 row */
    public ArrayList<Card> getOpenLevel1() { return openLevel1; }
    /** @return mutable face-up level-2 row */
    public ArrayList<Card> getOpenLevel2() { return openLevel2; }
    /** @return mutable face-up level-3 row */
    public ArrayList<Card> getOpenLevel3() { return openLevel3; }

    /** @return mutable closed level-1 deck */
    public ArrayList<Card> getClosedLevel1() { return closedLevel1; }
    /** @return mutable closed level-2 deck */
    public ArrayList<Card> getClosedLevel2() { return closedLevel2; }
    /** @return mutable closed level-3 deck */
    public ArrayList<Card> getClosedLevel3() { return closedLevel3; }

    /**
     * @param level {@code 1}, {@code 2}, or {@code 3}
     * @return open row for that level, or {@code null} if {@code level} is invalid
     */
    public ArrayList<Card> getOpenCardsByLevel(int level) {
        return switch (level) {
            case 1 -> openLevel1;
            case 2 -> openLevel2;
            case 3 -> openLevel3;
            default -> null;
        };
    }

    /**
     * @param level {@code 1}, {@code 2}, or {@code 3}
     * @return closed deck for that level, or {@code null} if {@code level} is invalid
     */
    public ArrayList<Card> getClosedCardsByLevel(int level) {
        return switch (level) {
            case 1 -> closedLevel1;
            case 2 -> closedLevel2;
            case 3 -> closedLevel3;
            default -> null;
        };
    }

    /** @return mutable list of nobles still available to visit */
    public ArrayList<Noble> getAvailNobles() { return availNobles; }

    /**
     * Removes a noble after a player acquires it.
     *
     * @param noble tile to remove (by equality in the list)
     */
    public void removeNoble(Noble noble) {
        availNobles.remove(noble);
    }

    /** @return mutable list of players in turn order */
    public ArrayList<Player> getPlayers() { return players; }

    /** @return index into {@link #getPlayers()} for whose turn it is */
    public int getCurrentPlayerIndex() { return currentPlayerIndex; }

    /**
     * @param index new current player index (caller must keep in range)
     */
    public void setCurrentPlayerIndex(int index) { this.currentPlayerIndex = index; }

    /** Advances {@code currentPlayerIndex} circularly to the next player. */
    public void advanceToNextPlayer() {
        currentPlayerIndex = (currentPlayerIndex + 1) % players.size();
    }

    /** @return the player whose turn it is */
    public Player getCurrentPlayer() {
        return players.get(currentPlayerIndex);
    }

    /** @return {@code true} once the game has ended */
    public boolean isGameOver() { return gameOver; }

    /**
     * @param gameOver whether the match has finished
     */
    public void setGameOver(boolean gameOver) { this.gameOver = gameOver; }

    /** @return {@code true} after someone has reached {@link #getPointsToWin()} and the final round is in progress */
    public boolean isFinalRound() { return finalRound; }

    /**
     * @param finalRound whether the game is in the closing round after hitting the prestige threshold
     */
    public void setFinalRound(boolean finalRound) { this.finalRound = finalRound; }

    /** @return prestige points needed to trigger the final round */
    public int getPointsToWin() { return pointsToWin; }

    /** @return maximum tokens a player may hold without returning gems */
    public int getMaxTokensPerPlayer() { return maxTokensPerPlayer; }
}
