// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game;

import org.springframework.stereotype.Service;
import com.splendor.web.game.model.Noble;
import com.splendor.web.game.model.Player;

import java.util.ArrayList;
import java.util.List;

/**
 * Assigns noble tiles when a player's purchased-card bonuses meet a noble's requirements.
 * Separate from {@link WebCardRulesService} (development cards).
 */
@Service
public class NobleAcquisitionService {

    /**
     * If the player qualifies for one or more available nobles, takes the first qualifying noble (deterministic order).
     *
     * @param session play state
     * @param player  player who just completed an action (typically current player at end of turn)
     * @return the noble acquired, or {@code null} if none qualified
     */
    public Noble processNobleAcquisition(GameSession session, Player player) {
        List<Noble> qualifying = new ArrayList<>();
        for (Noble n : session.getAvailNobles()) {
            if (playerHasEnoughBonuses(player, n)) qualifying.add(n);
        }
        if (qualifying.isEmpty()) return null;
        Noble chosen = qualifying.get(0);
        player.addNoble(chosen);
        session.removeNoble(chosen);
        return chosen;
    }

    /**
     * @param player the buyer's tableau
     * @param noble  candidate tile
     * @return {@code true} if each gem discount on bought cards meets the noble's requirement string
     */
    private boolean playerHasEnoughBonuses(Player player, Noble noble) {
        for (int i = 0; i < 5; i++) {
            int bonus = player.getBoughtCardsGemValueCount(i);
            int req = noble.getPurchasePrice().charAt(i) - '0';
            if (bonus < req) return false;
        }
        return true;
    }
}
