// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game;

/**
 * Immutable description of one player seat when starting a new game.
 * The list order passed to setup is turn order: index {@code 0} is youngest (starts first),
 * the last index is oldest.
 *
 * @param name  display name (may be blank; the server assigns {@code "Player N"} when empty)
 * @param human {@code true} for a human player, {@code false} for CPU
 */
public record PlayerSetup(String name, boolean human) {}
