// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game;

import org.springframework.stereotype.Service;
import com.splendor.web.game.model.Noble;
import com.splendor.web.game.model.Player;

/**
 * End-of-turn pipeline: automatic noble visit, final-round / game-over flags, then advance current player.
 */
@Service
public class TurnPhaseService {

    private final NobleAcquisitionService nobleAcquisition;

    /**
     * @param nobleAcquisition service that assigns qualifying nobles to the current player
     */
    public TurnPhaseService(NobleAcquisitionService nobleAcquisition) {
        this.nobleAcquisition = nobleAcquisition;
    }

    /**
     * Processes noble acquisition for the player who just acted, updates {@link GameSession} end-state flags,
     * and advances {@link GameSession#advanceToNextPlayer()}.
     *
     * @param session current game
     * @return the noble taken this step, or {@code null} if none
     */
    public Noble finishTurn(GameSession session) {
        Player player = session.getCurrentPlayer();
        Noble acquired = nobleAcquisition.processNobleAcquisition(session, player);
        checkGameEnd(session);
        session.advanceToNextPlayer();
        return acquired;
    }

    /**
     * Sets {@link GameSession#setFinalRound(boolean)} when any player reaches {@link GameSession#getPointsToWin()}.
     * Sets {@link GameSession#setGameOver(boolean)} when, during the final round, the last player in turn order has just finished.
     *
     * @param session current game
     */
    public void checkGameEnd(GameSession session) {
        for (Player p : session.getPlayers()) {
            if (p.getPrestigePoints() >= session.getPointsToWin()) {
                session.setFinalRound(true);
                break;
            }
        }
        if (session.isFinalRound() && session.getCurrentPlayerIndex() == session.getPlayers().size() - 1) {
            session.setGameOver(true);
        }
    }
}
