// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game;

import java.util.ArrayList;

import org.springframework.stereotype.Service;

import com.splendor.web.game.model.Card;
import com.splendor.web.game.model.Player;
import com.splendor.web.game.model.Token;

/**
 * Rules for development cards: reserve, buy, and paying with tokens.
 * Noble visits after a turn are handled by {@link NobleAcquisitionService} and {@link TurnPhaseService}.
 */
@Service
public class WebCardRulesService {

    private static final String[] GEM_COLORS = {"black", "blue", "green", "red", "white"};

    /**
     * Moves a face-up card into the current player's reserves and refills the slot; grants one gold if any remain.
     *
     * @param session current game
     * @param level   1, 2, or 3
     * @param index   position in the open row
     * @return {@code false} if reserves full, bad index, or empty row
     */
    public boolean reserveCardFromTable(GameSession session, int level, int index) {
        Player player = session.getCurrentPlayer();
        if (player.getReservedCards().size() >= 3) return false;
        ArrayList<Card> open = session.getOpenCardsByLevel(level);
        if (open == null || index < 0 || index >= open.size()) return false;

        Card card = open.remove(index);
        player.addReservedCard(card);
        if (session.getTokenCount("gold") > 0) {
            session.removeTokens("gold", 1);
            player.addToken(new Token("gold"));
        }
        refillOpen(session, level);
        return true;
    }

    /**
     * Takes the top card of the closed deck for the level into reserves; grants gold if available.
     *
     * @param session current game
     * @param level   1, 2, or 3
     * @return {@code false} if reserves full or deck empty
     */
    public boolean reserveCardFromDeck(GameSession session, int level) {
        Player player = session.getCurrentPlayer();
        if (player.getReservedCards().size() >= 3) return false;
        ArrayList<Card> closed = session.getClosedCardsByLevel(level);
        if (closed == null || closed.isEmpty()) return false;

        Card card = closed.remove(0);
        player.addReservedCard(card);
        if (session.getTokenCount("gold") > 0) {
            session.removeTokens("gold", 1);
            player.addToken(new Token("gold"));
        }
        return true;
    }

    /**
     * Purchases an open card if the current player can pay with gems (and gold as wildcard).
     *
     * @param session current game
     * @param level   card level
     * @param index   open-row index
     * @return {@code false} if unaffordable or bad index
     */
    public boolean buyCardFromTable(GameSession session, int level, int index) {
        ArrayList<Card> open = session.getOpenCardsByLevel(level);
        if (open == null || index < 0 || index >= open.size()) return false;
        Card card = open.get(index);
        return buyCard(session, card, open, index, false);
    }

    /**
     * Purchases a reserved card by index in the current player's hand.
     *
     * @param session       current game
     * @param reservedIndex slot in {@link Player#getReservedCards()}
     * @return {@code false} if unaffordable or bad index
     */
    public boolean buyReservedCard(GameSession session, int reservedIndex) {
        Player player = session.getCurrentPlayer();
        if (reservedIndex < 0 || reservedIndex >= player.getReservedCards().size()) return false;
        Card card = player.getReservedCards().get(reservedIndex);
        return buyCard(session, card, null, -1, true);
    }

    /**
     * Pays for {@code card}, removes it from the table or reserved list, adds it to bought cards, refills open row if needed.
     *
     * @param session      current game
     * @param card         card to buy
     * @param openList     open row when buying from table; {@code null} when buying from reserves
     * @param index        index in {@code openList} for table buy; ignored when {@code fromReserved}
     * @param fromReserved {@code true} when {@code card} comes from reserves
     * @return {@code false} if the player cannot afford the card
     */
    private boolean buyCard(GameSession session, Card card, ArrayList<Card> openList, int index, boolean fromReserved) {
        Player player = session.getCurrentPlayer();
        if (!canAfford(player, card)) return false;

        processPurchase(session, player, card);
        if (fromReserved) {
            player.removeReservedCard(card);
        } else {
            openList.remove(index);
            refillOpen(session, card.getLevel());
        }
        player.addBoughtCard(card);
        return true;
    }

    /**
     * @param player buyer
     * @param card   priced card
     * @return {@code true} if gems plus optional gold cover the discounted cost
     */
    private boolean canAfford(Player player, Card card) {
        int gold = player.getGoldTokenCount();
        for (int i = 0; i < 5; i++) {
            int cost = card.getPurchasePrice().charAt(i) - '0';
            int bonus = player.getBoughtCardsGemValueCount(i);
            int needed = Math.max(0, cost - bonus);
            int has = player.getGemTokenCount(i);
            if (has < needed) {
                if (gold < needed - has) return false;
                gold -= (needed - has);
            }
        }
        return true;
    }

    /**
     * Deducts the player's tokens and returns spent gems to the session bank (including gold used as wild).
     */
    private void processPurchase(GameSession session, Player player, Card card) {
        for (int i = 0; i < 5; i++) {
            int cost = card.getPurchasePrice().charAt(i) - '0';
            int bonus = player.getBoughtCardsGemValueCount(i);
            int needed = Math.max(0, cost - bonus);
            int toRemove = Math.min(player.getGemTokenCount(i), needed);
            if (toRemove > 0) {
                player.deductTokens(GEM_COLORS[i], toRemove);
                session.addTokens(GEM_COLORS[i], toRemove);
            }
            int goldNeeded = needed - toRemove;
            if (goldNeeded > 0) {
                player.deductTokens("gold", goldNeeded);
                session.addTokens("gold", goldNeeded);
            }
        }
    }

    /**
     * Draws random cards from the closed deck until the open row has four cards or the deck is empty.
     */
    private void refillOpen(GameSession session, int level) {
        ArrayList<Card> closed = session.getClosedCardsByLevel(level);
        ArrayList<Card> open = session.getOpenCardsByLevel(level);
        if (closed == null || open == null) return;
        CardSupply.transferRandomFaceUp(closed, open);
    }
}
