// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

import com.splendor.web.game.model.Card;
import com.splendor.web.game.model.Noble;
import com.splendor.web.game.model.Player;

/**
 * Heuristic AI for CPU players. Reads bank and market state from a {@link GameSession} and picks
 * Splendor actions in priority order: buy if possible, else reserve, else take two, else take three.
 */
public class WebCPUStrategy {

    private static final String[] GEM_COLORS = {"black", "blue", "green", "red", "white"};
    private static final Random RAND = new Random();
    private final GameSession session;

    /**
     * @param session game state to query (same session the CPU is playing in)
     */
    public WebCPUStrategy(GameSession session) {
        this.session = session;
    }

    /**
     * @param player the CPU player
     * @return action code {@code 1}=take three different, {@code 2}=take two same, {@code 3}=reserve, {@code 4}=buy
     */
    public int chooseAction(Player player) {
        if (findAffordableCard(player) >= 0) return 4;
        if (player.getReservedCards().size() < 3 && hasReservableCard()) return 3;
        if (canTake2Same()) return 2;
        if (canTake3Different()) return 1;
        return 1;
    }

    /**
     * Picks up to three distinct colours that still have bank chips, in shuffled order, space-separated.
     *
     * @param player unused today; reserved for future heuristics
     * @return string passed to {@link WebTokenRulesService#take3Tokens(GameSession, java.util.List)} after splitting
     */
    public String chooseThreeTokenColors(Player player) {
        List<String> available = new ArrayList<>();
        for (String color : GEM_COLORS) {
            if (session.getTokenCount(color) >= 1) available.add(color);
        }
        Collections.shuffle(available);
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < Math.min(3, available.size()); i++) {
            if (i > 0) sb.append(" ");
            sb.append(available.get(i));
        }
        return sb.toString();
    }

    /**
     * @param player unused today
     * @return first colour (in fixed gem order) with at least four tokens in the bank, or {@code black} as fallback
     */
    public String chooseTwoTokenColor(Player player) {
        for (String color : GEM_COLORS) {
            if (session.getTokenCount(color) >= 4) return color;
        }
        return GEM_COLORS[0];
    }

    /**
     * @param player unused today
     * @return {@code 1} to reserve from the table (face-up); {@code 2} would mean deck (see {@link CpuTurnService})
     */
    public int chooseReserveSource(Player player) {
        return 1; // Prefer face-up
    }

    /**
     * @param player unused today
     * @return lowest level (1→3) that still has at least one open card, default {@code 1}
     */
    public int chooseReserveLevel(Player player) {
        if (!session.getOpenLevel1().isEmpty()) return 1;
        if (!session.getOpenLevel2().isEmpty()) return 2;
        if (!session.getOpenLevel3().isEmpty()) return 3;
        return 1;
    }

    /**
     * @param player unused today
     * @param level  open row level
     * @return random valid index, or {@code 0} if the row is empty
     */
    public int chooseReserveCardIndex(Player player, int level) {
        ArrayList<Card> cards = session.getOpenCardsByLevel(level);
        if (cards == null || cards.isEmpty()) return 0;
        return RAND.nextInt(cards.size());
    }

    /**
     * @param player decision maker
     * @return {@code 2} if any reserved card is affordable, else {@code 1} for the table
     */
    public int chooseBuySource(Player player) {
        for (Card c : player.getReservedCards()) {
            if (canAfford(player, c)) return 2;
        }
        return 1;
    }

    /**
     * @param player buyer
     * @return highest level (3 down to 1) containing an affordable open card, else {@code 1}
     */
    public int chooseBuyLevel(Player player) {
        for (int level = 3; level >= 1; level--) {
            ArrayList<Card> cards = session.getOpenCardsByLevel(level);
            if (cards != null) {
                for (Card c : cards) {
                    if (canAfford(player, c)) return level;
                }
            }
        }
        return 1;
    }

    /**
     * @param player buyer
     * @param level  open row to search
     * @return index of an affordable card with maximal prestige in that row, or {@code 0} if none
     */
    public int chooseBuyCardIndex(Player player, int level) {
        ArrayList<Card> cards = session.getOpenCardsByLevel(level);
        if (cards == null || cards.isEmpty()) return 0;
        int bestIdx = 0;
        int bestPrestige = -1;
        for (int i = 0; i < cards.size(); i++) {
            if (canAfford(player, cards.get(i))) {
                int p = cards.get(i).getPrestigePoints();
                if (p > bestPrestige) {
                    bestPrestige = p;
                    bestIdx = i;
                }
            }
        }
        return bestIdx;
    }

    /**
     * @param player buyer
     * @return index of the first affordable reserved card, or {@code 0} if none affordable
     */
    public int chooseReservedCardIndex(Player player) {
        ArrayList<Card> reserved = player.getReservedCards();
        if (reserved.isEmpty()) return 0;
        for (int i = 0; i < reserved.size(); i++) {
            if (canAfford(player, reserved.get(i))) return i;
        }
        return 0;
    }

    /**
     * @param player player over the token limit
     * @return colour name of the gem type the player holds the most of (including gold)
     */
    public String chooseTokenToReturn(Player player) {
        int[] counts = new int[6];
        String[] names = {"black", "blue", "green", "red", "white", "gold"};
        for (int i = 0; i < 5; i++) counts[i] = player.getGemTokenCount(i);
        counts[5] = player.getGoldTokenCount();
        int maxIdx = 0;
        for (int i = 1; i < 6; i++) {
            if (counts[i] > counts[maxIdx]) maxIdx = i;
        }
        return names[maxIdx];
    }

    /**
     * @param player unused today
     * @param nobles qualifying nobles (non-empty)
     * @return random index into {@code nobles}
     */
    public int chooseNoble(Player player, ArrayList<Noble> nobles) {
        return RAND.nextInt(nobles.size());
    }

    /**
     * @param player buyer
     * @param card   priced development card
     * @return {@code true} if discounts plus gems and gold cover the cost
     */
    private boolean canAfford(Player player, Card card) {
        int gold = player.getGoldTokenCount();
        for (int i = 0; i < 5; i++) {
            int cost = card.getPurchasePrice().charAt(i) - '0';
            int bonus = player.getBoughtCardsGemValueCount(i);
            int needed = Math.max(0, cost - bonus);
            int has = player.getGemTokenCount(i);
            if (has < needed) {
                if (gold < needed - has) return false;
                gold -= (needed - has);
            }
        }
        return true;
    }

    /**
     * @param player buyer
     * @return non-negative if any reserved or open card is affordable, else {@code -1}
     */
    private int findAffordableCard(Player player) {
        for (Card c : player.getReservedCards()) {
            if (canAfford(player, c)) return 1;
        }
        for (int level = 1; level <= 3; level++) {
            ArrayList<Card> cards = session.getOpenCardsByLevel(level);
            if (cards != null) {
                for (Card c : cards) {
                    if (canAfford(player, c)) return 1;
                }
            }
        }
        return -1;
    }

    /** @return {@code true} if any open row has at least one card */
    private boolean hasReservableCard() {
        return !session.getOpenLevel1().isEmpty()
                || !session.getOpenLevel2().isEmpty()
                || !session.getOpenLevel3().isEmpty();
    }

    /** @return {@code true} if some colour has four or more tokens in the bank */
    private boolean canTake2Same() {
        for (String c : GEM_COLORS) {
            if (session.getTokenCount(c) >= 4) return true;
        }
        return false;
    }

    /** @return {@code true} if at least three colours each have one or more tokens in the bank */
    private boolean canTake3Different() {
        int count = 0;
        for (String c : GEM_COLORS) {
            if (session.getTokenCount(c) >= 1) count++;
        }
        return count >= 3;
    }
}
