// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.springframework.stereotype.Service;

import com.splendor.web.game.data.DataLoader;
import com.splendor.web.game.model.Card;
import com.splendor.web.game.model.Noble;

/**
 * Builds a fresh {@link GameSession}: reads configuration and CSV data, shuffles decks,
 * deals face-up cards, and selects nobles for the player count.
 */
@Service
public class WebGameSetupService {

    private final DataLoader dataLoader = new DataLoader();

    /**
     * Creates a new game with bank tokens, shuffled development cards, and the correct noble count.
     *
     * @param playersInTurnOrder first entry is youngest (goes first); last is oldest
     * @return new mutable session ready for play
     */
    public GameSession newGame(List<PlayerSetup> playersInTurnOrder) {
        int playerCount = playersInTurnOrder.size();
        int pointsToWin = Integer.parseInt(dataLoader.getProperty("game.pointsToWin"));
        int maxTokens = Integer.parseInt(dataLoader.getProperty("game.maxTokensPerPlayer"));
        int tokenPerGem = Integer.parseInt(dataLoader.getProperty("game.tokenCount." + playerCount + "players"));
        int goldCount = Integer.parseInt(dataLoader.getProperty("game.tokenCount.gold"));

        GameSession session = new GameSession(playersInTurnOrder, pointsToWin, maxTokens, tokenPerGem, goldCount);

        loadCards(session);
        loadNobles(session, playerCount);

        return session;
    }

    /**
     * Parses {@code cards.csv} (path from config) into closed decks by level, shuffles implicitly via
     * {@link CardSupply#transferRandomFaceUp}, and fills each open row.
     *
     * @param session session whose card lists are filled
     */
    private void loadCards(GameSession session) {
        String path = dataLoader.getProperty("file.cards");
        if (path == null || path.isBlank()) {
            path = "/cards.csv";
        }
        String content = dataLoader.readResourceFile(path);
        String[] lines = content.split("\n");
        ArrayList<Card> closed1 = session.getClosedLevel1();
        ArrayList<Card> closed2 = session.getClosedLevel2();
        ArrayList<Card> closed3 = session.getClosedLevel3();

        for (int i = 1; i < lines.length; i++) {
            String[] p = lines[i].split(",");
            int level = Integer.parseInt(p[0]);
            String color = p[1];
            int prestige = Integer.parseInt(p[2]);
            StringBuilder price = new StringBuilder();
            for (int j = 3; j <= 7; j++) price.append(p[j]);
            Card card = new Card(level, color, prestige, price.toString());
            switch (level) {
                case 1 -> closed1.add(card);
                case 2 -> closed2.add(card);
                case 3 -> closed3.add(card);
            }
        }

        CardSupply.transferRandomFaceUp(session.getClosedLevel1(), session.getOpenLevel1());
        CardSupply.transferRandomFaceUp(session.getClosedLevel2(), session.getOpenLevel2());
        CardSupply.transferRandomFaceUp(session.getClosedLevel3(), session.getOpenLevel3());
    }

    /**
     * Loads all nobles from CSV, shuffles, then adds {@code min(playerCount + 1, total)} to the session.
     *
     * @param session      session whose available-noble list is filled
     * @param playerCount  number of players (determines how many nobles are in play)
     */
    private void loadNobles(GameSession session, int playerCount) {
        String path = dataLoader.getProperty("file.nobles");
        if (path == null || path.isBlank()) {
            path = "/nobles.csv";
        }
        String content = dataLoader.readResourceFile(path);
        String[] lines = content.split("\n");
        ArrayList<Noble> all = new ArrayList<>();
        for (int i = 1; i < lines.length; i++) {
            String[] p = lines[i].split(",");
            String name = p[0];
            int prestige = Integer.parseInt(p[1]);
            StringBuilder price = new StringBuilder();
            for (int j = 2; j <= 6; j++) price.append(p[j]);
            all.add(new Noble(name, prestige, price.toString()));
        }
        Collections.shuffle(all);
        int count = Math.min(playerCount + 1, all.size());
        for (int i = 0; i < count; i++) {
            session.getAvailNobles().add(all.get(i));
        }
    }
}
