// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game;

import java.util.List;

import org.springframework.stereotype.Service;

import com.splendor.web.game.model.Player;
import com.splendor.web.game.model.Token;

/**
 * Splendor token actions against a {@link GameSession} bank: take three distinct, take two same,
 * and return excess when over {@link GameSession#getMaxTokensPerPlayer()}.
 */
@Service
public class WebTokenRulesService {

    /**
     * Takes one token of each of three distinct colours from the bank for the current player.
     *
     * @param session current game
     * @param colors exactly three distinct non-gold gem names with at least one chip each in the bank
     * @return {@code false} if validation fails; otherwise {@code true} and state is updated
     */
    public boolean take3Tokens(GameSession session, List<String> colors) {
        if (colors == null || colors.size() != 3) return false;
        if (new java.util.HashSet<>(colors).size() != 3) return false;
        for (String c : colors) {
            if (!Token.checkGemType(c) || session.getTokenCount(c) < 1) return false;
        }
        Player p = session.getCurrentPlayer();
        for (String c : colors) {
            session.removeTokens(c, 1);
            p.addToken(new Token(c));
        }
        return true;
    }

    /**
     * Takes two tokens of the same colour when the bank holds at least four of that colour.
     *
     * @param session current game
     * @param color   valid non-gold gem colour
     * @return {@code false} if the bank has fewer than four or colour is invalid
     */
    public boolean take2Tokens(GameSession session, String color) {
        if (!Token.checkGemType(color) || session.getTokenCount(color) < 4) return false;
        Player player = session.getCurrentPlayer();
        session.removeTokens(color, 2);
        player.addToken(new Token(color));
        player.addToken(new Token(color));
        return true;
    }

    /**
     * Returns gems from the current player to the bank until at or under the token limit,
     * processing {@code tokensToReturn} in order (one removal per listed colour per iteration).
     *
     * @param session         current game
     * @param tokensToReturn  colours to return; typically sized to clear excess over {@link GameSession#getMaxTokensPerPlayer()}
     */
    public void executeReturnTokens(GameSession session, List<String> tokensToReturn) {
        Player player = session.getCurrentPlayer();
        for (String gem : tokensToReturn) {
            if (player.getTokens().size() <= session.getMaxTokensPerPlayer()) break;
            player.deductTokens(gem, 1);
            session.addTokens(gem, 1);
        }
    }
}
