// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.controller;

import java.util.Arrays;
import java.util.List;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import jakarta.servlet.http.HttpSession;
import com.splendor.web.game.GameService;
import com.splendor.web.game.GameSession;
import com.splendor.web.game.model.Player;

/**
 * Spring MVC controller for in-progress gameplay: rendering the board, handling human actions
 * via form posts, and delegating turn completion and CPU turns to {@link GameService}.
 * <p>
 * Game state is read from the HTTP session attribute {@code "gameSession"} ({@link GameSession}).
 */
@Controller
public class GameController {

    private final GameService gameService;

    /**
     * @param gameService facade for token, card, turn, and CPU logic
     */
    public GameController(GameService gameService) {
        this.gameService = gameService;
    }

    /**
     * Main game entry: loads session state and returns the appropriate view.
     * <p>
     * If there is no session game, redirects home. If the game has ended, shows {@code game-over}.
     * If the current player is human, shows {@code game} (optionally with tour). Otherwise runs
     * one CPU turn and shows {@code cpu-turn} with a play-by-play log.
     *
     * @param session HTTP session containing {@code "gameSession"}; may contain {@code "showTour"}
     * @param model   receives {@code gameSession}, and view-specific attributes (winners, CPU log, etc.)
     * @param ra      used when redirecting home with flash {@code error} if no game exists
     * @return view name {@code game}, {@code game-over}, or {@code cpu-turn}, or {@code redirect:/}
     */
    @GetMapping("/game")
    public String game(HttpSession session, Model model, RedirectAttributes ra) {
        GameSession gs = (GameSession) session.getAttribute("gameSession");
        if (gs == null) {
            ra.addFlashAttribute("error", "No game in progress.");
            return "redirect:/";
        }
        if (gs.isGameOver()) {
            model.addAttribute("gameSession", gs);
            model.addAttribute("winnerIds", gameService.computeWinnerPlayerIds(gs));
            return "game-over";
        }
        Player current = gs.getCurrentPlayer();
        if (current.isHuman()) {
            model.addAttribute("gameSession", gs);
            model.addAttribute("overTokenLimit", current.getTokens().size() > gs.getMaxTokensPerPlayer());
            if (Boolean.TRUE.equals(session.getAttribute("showTour"))) {
                model.addAttribute("showTour", true);
                session.removeAttribute("showTour");
            }
            return "game";
        }
        List<String> log = gameService.executeOneCPUTurn(gs);
        model.addAttribute("gameSession", gs);
        model.addAttribute("cpuTurnLog", log);
        model.addAttribute("cpuPlayerName", current.getDisplayName());
        return "cpu-turn";
    }

    /**
     * Handles "take three different coloured tokens" when it is the current human player's turn.
     *
     * @param color1  first gem colour (case-insensitive)
     * @param color2  second gem colour, distinct from the others per rules
     * @param color3  third gem colour
     * @param session HTTP session holding {@code "gameSession"}
     * @param ra      flash attributes for errors or success / return-token flow
     * @return redirect to {@code /} if no session game, {@code /game} otherwise
     */
    @PostMapping("/game/take3")
    public String take3(@RequestParam String color1, @RequestParam String color2, @RequestParam String color3,
                        HttpSession session, RedirectAttributes ra) {
        GameSession gs = getSession(session, ra);
        if (gs == null) return "redirect:/";
        List<String> colors = Arrays.asList(color1.toLowerCase(), color2.toLowerCase(), color3.toLowerCase());
        if (!gameService.take3Tokens(gs, colors)) {
            ra.addFlashAttribute("error", "Invalid take-3 selection. Pick 3 different colors with tokens available.");
            return "redirect:/game";
        }
        return finishOrReturnTokens(gs, ra, "Tokens taken.");
    }

    /**
     * Handles "take two tokens of the same colour" when the bank has at least four of that colour.
     *
     * @param color   gem colour (case-insensitive)
     * @param session HTTP session holding {@code "gameSession"}
     * @param ra      flash attributes for errors or success / return-token flow
     * @return redirect to {@code /} if no session game, {@code /game} otherwise
     */
    @PostMapping("/game/take2")
    public String take2(@RequestParam String color, HttpSession session, RedirectAttributes ra) {
        GameSession gs = getSession(session, ra);
        if (gs == null) return "redirect:/";
        if (!gameService.take2Tokens(gs, color.toLowerCase())) {
            ra.addFlashAttribute("error", "Invalid take-2 selection. That color needs 4+ tokens in the pile.");
            return "redirect:/game";
        }
        return finishOrReturnTokens(gs, ra, "Tokens taken.");
    }

    /**
     * Reserves a face-up development card from the table for the current player (gold taken if available).
     *
     * @param level   card level (1, 2, or 3)
     * @param index   index within the open row for that level
     * @param session HTTP session holding {@code "gameSession"}
     * @param ra      flash attributes for errors or success / return-token flow
     * @return redirect to {@code /} or {@code /game}
     */
    @PostMapping("/game/reserve-table")
    public String reserveTable(@RequestParam int level, @RequestParam int index, HttpSession session, RedirectAttributes ra) {
        GameSession gs = getSession(session, ra);
        if (gs == null) return "redirect:/";
        if (!gameService.reserveCardFromTable(gs, level, index)) {
            ra.addFlashAttribute("error", "Invalid reserve selection. You may already have 3 reserved cards.");
            return "redirect:/game";
        }
        return finishOrReturnTokens(gs, ra, "Card reserved.");
    }

    /**
     * Reserves the top card from the closed deck of the given level without revealing it to others
     * in the UI beyond the reserve action.
     *
     * @param level   deck level (1, 2, or 3)
     * @param session HTTP session holding {@code "gameSession"}
     * @param ra      flash attributes for errors or success / return-token flow
     * @return redirect to {@code /} or {@code /game}
     */
    @PostMapping("/game/reserve-deck")
    public String reserveDeck(@RequestParam int level, HttpSession session, RedirectAttributes ra) {
        GameSession gs = getSession(session, ra);
        if (gs == null) return "redirect:/";
        if (!gameService.reserveCardFromDeck(gs, level)) {
            ra.addFlashAttribute("error", "Invalid reserve from deck. You may already have 3 reserved cards.");
            return "redirect:/game";
        }
        return finishOrReturnTokens(gs, ra, "Card reserved.");
    }

    /**
     * Purchases a face-up development card from the table using the current player's tokens (and gold as wild).
     *
     * @param level   card level (1, 2, or 3)
     * @param index   index within the open row for that level
     * @param session HTTP session holding {@code "gameSession"}
     * @param ra      flash attributes for errors or success / return-token flow
     * @return redirect to {@code /} or {@code /game}
     */
    @PostMapping("/game/buy-table")
    public String buyTable(@RequestParam int level, @RequestParam int index, HttpSession session, RedirectAttributes ra) {
        GameSession gs = getSession(session, ra);
        if (gs == null) return "redirect:/";
        if (!gameService.buyCardFromTable(gs, level, index)) {
            ra.addFlashAttribute("error", "Cannot buy that card. Check you have enough tokens (including gold as wildcards).");
            return "redirect:/game";
        }
        return finishOrReturnTokens(gs, ra, "Card purchased.");
    }

    /**
     * Purchases a card from the current player's reserved hand by slot index.
     *
     * @param index   index of the reserved card to buy
     * @param session HTTP session holding {@code "gameSession"}
     * @param ra      flash attributes for errors or success / return-token flow
     * @return redirect to {@code /} or {@code /game}
     */
    @PostMapping("/game/buy-reserved")
    public String buyReserved(@RequestParam int index, HttpSession session, RedirectAttributes ra) {
        GameSession gs = getSession(session, ra);
        if (gs == null) return "redirect:/";
        if (!gameService.buyReservedCard(gs, index)) {
            ra.addFlashAttribute("error", "Cannot buy that reserved card. Check you have enough tokens.");
            return "redirect:/game";
        }
        return finishOrReturnTokens(gs, ra, "Card purchased.");
    }

    /**
     * Returns excess tokens to the bank when the current player is over the per-player token limit.
     * Completes the turn once the player is back at or under the limit.
     *
     * @param tokens  colours to return; must include at least as many entries as the current excess
     * @param session HTTP session holding {@code "gameSession"}
     * @param ra      flash {@code error} if too few tokens selected, or {@code success} when turn ends
     * @return redirect to {@code /} or {@code /game}
     */
    @PostMapping("/game/return-tokens")
    public String returnTokens(@RequestParam(required = false) List<String> tokens, HttpSession session, RedirectAttributes ra) {
        GameSession gs = getSession(session, ra);
        if (gs == null) return "redirect:/";
        int excess = gs.getCurrentPlayer().getTokens().size() - gs.getMaxTokensPerPlayer();
        if (tokens == null || tokens.size() < excess) {
            ra.addFlashAttribute("error", "Select exactly " + excess + " token(s) to return.");
            return "redirect:/game";
        }
        gameService.executeReturnTokens(gs, tokens.subList(0, excess));
        if (gs.getCurrentPlayer().getTokens().size() <= gs.getMaxTokensPerPlayer()) {
            gameService.finishTurn(gs);
            ra.addFlashAttribute("success", "Turn complete. Next player's turn.");
        }
        return "redirect:/game";
    }

    /**
     * After an action that may add tokens, either ends the turn or forces the return-tokens UI.
     *
     * @param gs         mutable session game state
     * @param ra         receives {@code returnRequired} or flash {@code success}
     * @param successMsg prefix message when the turn completes immediately (tokens within limit)
     * @return {@code redirect:/game}
     */
    private String finishOrReturnTokens(GameSession gs, RedirectAttributes ra, String successMsg) {
        Player p = gs.getCurrentPlayer();
        if (p.getTokens().size() > gs.getMaxTokensPerPlayer()) {
            ra.addFlashAttribute("returnRequired", true);
            return "redirect:/game";
        }
        gameService.finishTurn(gs);
        ra.addFlashAttribute("success", successMsg + " Turn complete.");
        return "redirect:/game";
    }

    /**
     * Reads the game from the HTTP session and sets a flash error if it is missing.
     *
     * @param session servlet session
     * @param ra      receives flash {@code "error"} when there is no {@code "gameSession"}
     * @return the {@link GameSession}, or {@code null} if absent
     */
    private GameSession getSession(HttpSession session, RedirectAttributes ra) {
        GameSession gs = (GameSession) session.getAttribute("gameSession");
        if (gs == null) ra.addFlashAttribute("error", "No game in progress.");
        return gs;
    }
}
