// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.controller;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.servlet.http.HttpSession;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import com.splendor.web.game.GameService;
import com.splendor.web.game.GameSession;
import com.splendor.web.game.PlayerSetup;

import java.util.ArrayList;
import java.util.List;

/**
 * Spring MVC controller for the home page and starting a new game.
 * <p>
 * Validates JSON player setup from the client, builds a {@link GameSession}
 * via {@link GameService}, and stores it in the HTTP session before redirecting to the game view.
 */
@Controller
public class HomeController {

    private final GameService gameService;
    private final ObjectMapper objectMapper;

    /**
     * Creates the controller with game logic and JSON parsing dependencies.
     *
     * @param gameService   service used to construct a new {@code GameSession} from player setup
     * @param objectMapper  Jackson mapper used to deserialize {@code playersJson} into payloads
     */
    public HomeController(GameService gameService, ObjectMapper objectMapper) {
        this.gameService = gameService;
        this.objectMapper = objectMapper;
    }

    /**
     * Serves the new-game setup page at the application root.
     *
     * @param model Spring MVC model (unused for the index view as provided)
     * @return logical view name {@code "index"}
     */
    @GetMapping("/")
    public String index(Model model) {
        return "index";
    }

    /**
     * Accepts posted player configuration, starts a new game, and redirects to {@code /game}.
     * <p>
     * Expects {@code playersJson} to be a JSON array of {@link PlayerSetupPayload} objects
     * (2–4 players). On validation or parse failure, redirects to {@code /} with a flash error.
     *
     * @param playersJson JSON array string: {@code [{"name":"...","human":true}, ...]}
     * @param session     HTTP session; receives attribute {@code "gameSession"} and {@code "showTour"}
     * @param ra          redirect flash attributes for errors when setup is invalid
     * @return redirect to {@code /game} on success, or {@code redirect:/} with flash {@code error}
     */
    @PostMapping("/new-game")
    public String newGame(@RequestParam("playersJson") String playersJson,
                          HttpSession session,
                          RedirectAttributes ra) {
        if (playersJson == null || playersJson.isBlank()) {
            ra.addFlashAttribute("error", "Add 2–4 players with names and types.");
            return "redirect:/";
        }
        List<PlayerSetupPayload> payloads;
        try {
            payloads = objectMapper.readValue(playersJson, new TypeReference<List<PlayerSetupPayload>>() {});
        } catch (Exception e) {
            ra.addFlashAttribute("error", "Invalid player data. Please try again.");
            return "redirect:/";
        }
        if (payloads == null || payloads.size() < 2 || payloads.size() > 4) {
            ra.addFlashAttribute("error", "You need between 2 and 4 players.");
            return "redirect:/";
        }

        List<PlayerSetup> slots = new ArrayList<>(payloads.size());
        for (PlayerSetupPayload p : payloads) {
            slots.add(new PlayerSetup(p.getName() != null ? p.getName() : "", p.isHuman()));
        }

        GameSession gameSession = gameService.newGame(slots);
        session.setAttribute("gameSession", gameSession);
        session.setAttribute("showTour", true);
        return "redirect:/game";
    }
}
