// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.controller;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Data transfer object for one row of the new-game form, deserialized from JSON posted as
 * {@code playersJson}. Shape: {@code {"name":"...","human":true}}.
 * <p>
 * Unknown JSON properties are ignored so the client can evolve without breaking parsing.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class PlayerSetupPayload {
    private String name;
    private boolean human;

    /**
     * @return display name for this player; may be {@code null} before binding
     */
    public String getName() {
        return name;
    }

    /**
     * @param name display name for this player (empty string is normalized later in {@link HomeController})
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return {@code true} if this slot is a human player, {@code false} for CPU
     */
    public boolean isHuman() {
        return human;
    }

    /**
     * @param human {@code true} for human, {@code false} for CPU
     */
    public void setHuman(boolean human) {
        this.human = human;
    }
}
