// Documentation comments generated by Claude and manually vetted 
package com.splendor;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Entry point for the Splendor web application.
 * <p>
 * Bootstraps a Spring Boot context with component scanning, auto-configuration,
 * and embedded web server support for the Splendor game UI and REST endpoints.
 */
@SpringBootApplication
public class SplendorApplication {

    /**
     * Starts the Spring application and runs the embedded server.
     *
     * @param args command-line arguments passed to the JVM (forwarded to Spring Boot)
     */
    public static void main(String[] args) {
        SpringApplication.run(SplendorApplication.class, args);
    }
}
