// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game.model;

import java.io.Serializable;

/**
 * A development card: level, gem discount colour, prestige points, and a five-digit cost string
 * (black→white order) used by purchase and noble logic.
 */
public class Card implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String gemType;
    private final String purchasePrice;
    private final int prestigePoints;
    private final int level;

    /**
     * @param level          tier {@code 1}, {@code 2}, or {@code 3}
     * @param gemType        discount colour this card grants when bought
     * @param prestigePoints victory points printed on the card
     * @param purchasePrice  five characters, each {@code '0'}–{@code '9'}, costs for black, blue, green, red, white
     */
    public Card(int level, String gemType, int prestigePoints, String purchasePrice) {
        this.level = level;
        this.gemType = gemType;
        this.prestigePoints = prestigePoints;
        this.purchasePrice = purchasePrice;
    }

    /** @return card tier (1–3) */
    public int getLevel() {
        return level;
    }

    /** @return gem type string for discounts (e.g. web/UI colour key) */
    public String getGemType() {
        return gemType;
    }

    /** @return prestige points awarded when this card is purchased */
    public int getPrestigePoints() {
        return prestigePoints;
    }

    /** @return five-character cost encoding */
    public String getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * @param tokenColor black, blue, green, red, or white (case-insensitive)
     * @return digit from the cost string for that colour, or {@code 0} for unknown colours
     */
    public int getPrice(String tokenColor) {
        switch (tokenColor.toLowerCase()) {
            case "black": return purchasePrice.charAt(0) - '0';
            case "blue": return purchasePrice.charAt(1) - '0';
            case "green": return purchasePrice.charAt(2) - '0';
            case "red": return purchasePrice.charAt(3) - '0';
            case "white": return purchasePrice.charAt(4) - '0';
            default: return 0;
        }
    }

    /**
     * @return multi-line summary for debugging or CLI-style output
     */
    @Override
    public String toString() {
        return "Level: " + level + " | Gem Type: " + gemType + " | Points: " + prestigePoints +
                "\n      Price -> Black: " + getPrice("black") + " | Blue: " + getPrice("blue") + " | Green: "
                + getPrice("green") + " | Red: " + getPrice("red") + " | White: " + getPrice("white");
    }
}
