// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Mutable per-player state during a game: gem chips, reserved and purchased development cards,
 * acquired nobles, running prestige total, and display metadata (id, human flag, name).
 */
public class Player implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final String[] TOKEN_ORDER = {"black", "blue", "green", "red", "white", "gold"};
    private final int playerID;
    private final boolean isHuman;
    private final String displayName;
    private int prestigePoints = 0;
    private ArrayList<Token> tokens = new ArrayList<>();
    private ArrayList<Card> boughtCards = new ArrayList<>();
    private ArrayList<Card> reservedCards = new ArrayList<>();
    private ArrayList<Noble> nobles = new ArrayList<>();

    /**
     * @param playerID    stable numeric id
     * @param isHuman     {@code true} for human-controlled seat
     * @param displayName trimmed to 48 chars; empty becomes {@code "Player " + playerID}
     */
    public Player(int playerID, boolean isHuman, String displayName) {
        this.playerID = playerID;
        this.isHuman = isHuman;
        String t = displayName == null ? "" : displayName.trim();
        if (t.length() > 48) {
            t = t.substring(0, 48);
        }
        this.displayName = t.isEmpty() ? "Player " + playerID : t;
    }

    /** @return UI / log name */
    public String getDisplayName() {
        return displayName;
    }

    /** @return {@code true} if this seat is human */
    public boolean isHuman() {
        return isHuman;
    }

    /** @return numeric player id */
    public int getPlayerID() {
        return playerID;
    }

    /** @return prestige from cards and nobles */
    public int getPrestigePoints() {
        return prestigePoints;
    }

    /** @return live list of chips in hand (unordered) */
    public ArrayList<Token> getTokens() {
        return tokens;
    }

    /**
     * @return a new list of tokens ordered black, blue, green, red, white, then gold
     */
    public List<Token> getTokensSorted() {
        ArrayList<Token> sorted = new ArrayList<>(tokens);
        sorted.sort(Comparator.comparingInt(t -> {
            for (int i = 0; i < TOKEN_ORDER.length; i++) {
                if (TOKEN_ORDER[i].equals(t.getGemType().toLowerCase())) return i;
            }
            return TOKEN_ORDER.length;
        }));
        return sorted;
    }

    /** @return purchased development cards */
    public ArrayList<Card> getBoughtCards() {
        return boughtCards;
    }

    /** @return reserved cards (max three in rules) */
    public ArrayList<Card> getReservedCards() {
        return reservedCards;
    }

    /** @return nobles that have visited this player */
    public ArrayList<Noble> getNobles() {
        return nobles;
    }

    /**
     * @param token chip to add to hand
     */
    public void addToken(Token token) {
        tokens.add(token);
    }

    /**
     * @param card reserved from table or deck
     */
    public void addReservedCard(Card card) {
        this.reservedCards.add(card);
    }

    /**
     * @param card exact instance to remove from reserves
     */
    public void removeReservedCard(Card card) {
        this.reservedCards.remove(card);
    }

    /**
     * Moves a card to the tableau and increases prestige by the card's points.
     *
     * @param card purchased card
     */
    public void addBoughtCard(Card card) {
        this.boughtCards.add(card);
        this.prestigePoints += card.getPrestigePoints();
    }

    /**
     * @param noble acquired noble tile
     */
    public void addNoble(Noble noble) {
        this.nobles.add(noble);
        this.prestigePoints += noble.getPrestigePoints();
    }

    /**
     * @param gemTypeIndex {@code 0}=black … {@code 4}=white
     * @return count of non-gold tokens of that colour
     */
    public int getGemTokenCount(int gemTypeIndex) {
        String[] gemTypes = {"black", "blue", "green", "red", "white"};
        String targetGem = gemTypes[gemTypeIndex];
        int count = 0;
        for (Token token : tokens) {
            if (token.getGemType().equals(targetGem)) {
                count++;
            }
        }
        return count;
    }

    /** @return number of gold (wildcard) tokens held */
    public int getGoldTokenCount() {
        int count = 0;
        for (Token token : tokens) {
            if (token.getGemType().equals("gold")) {
                count++;
            }
        }
        return count;
    }

    /**
     * Counts bought cards whose discount colour matches the given index (for purchase/noble math).
     *
     * @param gemTypeIndex {@code 0}=black … {@code 4}=white
     * @return how many bought cards provide that gem discount
     */
    public int getBoughtCardsGemValueCount(int gemTypeIndex) {
        String[] gemTypes = {"black", "blue", "green", "red", "white"};
        String targetGem = gemTypes[gemTypeIndex];
        int count = 0;

        for (Card card : boughtCards) {
            if (card.getGemType().toLowerCase().equals(targetGem)) {
                count++;
            }
        }
        return count;
    }

    /**
     * Removes non-gold or gold tokens by palette index without updating the bank (legacy/helper).
     *
     * @param gemTypeIndex   {@code 0}–{@code 4} standard colours, {@code 5} gold
     * @param numberOfTokens how many to remove from the end of matching tokens
     */
    public void removePlayerTokens(int gemTypeIndex, int numberOfTokens) {
        String[] gemTypes = {"black", "blue", "green", "red", "white", "gold"};
        String targetGem = gemTypes[gemTypeIndex];

        int removed = 0;

        for (int i = getTokens().size() - 1; i >= 0 && removed < numberOfTokens; i--) {
            if (getTokens().get(i).getGemType().equals(targetGem)) {
                getTokens().remove(i);
                removed++;
            }
        }
    }

    /**
     * Removes up to {@code numberOfTokens} chips matching {@code gemType} from the player's hand only.
     * The caller is responsible for returning those gems to {@link com.splendor.web.game.GameSession}.
     *
     * @param gemType        e.g. {@code "red"} or {@code "gold"}
     * @param numberOfTokens maximum removals
     */
    public void deductTokens(String gemType, int numberOfTokens) {
        int removed = 0;
        for (int i = getTokens().size() - 1; i >= 0 && removed < numberOfTokens; i--) {
            if (getTokens().get(i).getGemType().equals(gemType)) {
                getTokens().remove(i);
                removed++;
            }
        }
    }
}
