// Documentation comments generated by Claude and manually vetted 
package com.splendor.web.game.model;

import java.io.Serializable;

/**
 * One gem chip in a player's hand. Gold is represented with type {@code "gold"} but is not
 * validated by {@link #checkGemType(String)} (reserved for standard colours only).
 */
public class Token implements Serializable {

    private static final long serialVersionUID = 1L;

    private String gemType;

    /**
     * @param gemType colour key, e.g. {@code "red"} or {@code "gold"}
     */
    public Token(String gemType) {
        this.gemType = gemType;
    }

    /**
     * @param gemType candidate colour
     * @return {@code true} for black, blue, green, red, or white (case-insensitive)
     */
    public static boolean checkGemType(String gemType) {
        switch (gemType.toLowerCase()) {
            case "white":
            case "blue":
            case "green":
            case "red":
            case "black":
                return true;
            default:
                return false;
        }
    }

    /** @return gem colour key */
    public String getGemType() {
        return this.gemType;
    }

    /** {@inheritDoc} */
    @Override
    public String toString() {
        return gemType;
    }
}
